### ISSUE TITLE
Use Library

### ISSUE THREAD

**Issue by Amirmohammadkazemi** [mahanfr/Nmet#3]
I want to develop the std library. But in your examples I can't see the use of the library property. Does your programming language support the use of the library? If yes how can I use this feature?

**Comment by mahanfr** [comment]
Hi, We currently have no way to include external functions as the compiler can only compile a single file. I will notify you in this issue when the functionality gets added.

**Comment by mahanfr** [comment]
Support for imports has been added in commit [c1cf3b8](https://github.com/mahanfarzaneh2000/Nemet/tree/c1cf3b8f2988dc1d54c207996a5111b1e24c40dd)

Grammars added:
* import "./std/syscalls"
* import "./std/syscalls" :: sys_write, sys_exit

Warning: Make sure that you do not import functions with the same name or
do not import the same file twice :)
**we will fix these problems in the future!**

**Comment by Amirmohammadkazemi** [comment]
Thank you very much
